### ISSUE TITLE
Global merge required

### ISSUE THREAD

**Issue by rasmusbj** [cmt-dtu-energy/MagTense#13]
A merge of the different branches are in order...

**Comment by kasparn** [comment]
Did the merge of the ODE branch into the Master branch. It compiles and runs... :)

**Comment by rasmusbj** [comment]
You like opening and closing branches? 😁

**Comment by kasparn** [comment]
Yes!

Thought it was the comment...

man. 17. feb. 2020 22.13 skrev rasmusbj <notifications@github.com>:

**Comment by rasmusbj** [comment]
CVODE is now merged into the master branch, as is ODE. Closing this issue
