### ISSUE TITLE
Examples of permanent magnets with 3D polarization

### ISSUE THREAD

**Issue by zhucaoxiang** [cmt-dtu-energy/MagTense#18]
Hi, I am trying to find a tool calculating the magnetic field from a permanent magnet (with or without constant mu). The magnet is cuboidal, but the magnetization direction is not necessarily normal to faces and is arbitrary in 3D space. Like a generic case of the one you show on the webpage. I am wondering if this can be realized the MagTense? If yes, do you have some examples? Thanks in advance!

![image](https://user-images.githubusercontent.com/26240833/138705437-f92459ea-e442-4dee-b0d7-199dd283779e.png)

**Comment by rasmusbj** [comment]
The examples has been pushed on the main Git branch and thus I will close this issue for now. It can always be reopened :)

**Comment by zhucaoxiang** [comment]
@rasmusbj Hi, thanks for the example. I am able to do some interesting calculations. I am wondering 
1. How to read cutomized B-H data (any documentation in the format)?
2. Is it possible to provide an external field?

Thank you in advance.

**Comment by zhucaoxiang** [comment]
@spollok Maybe I should assign you.

**Comment by spollok** [comment]
@zhucaoxiang No worries. I got notified of the questions :)
To 1.) I will update the documentation on it today.
To 2.) Currently, that is not possible in the magnetostatic part. I had a discussion on it with @rasmusbj already and it is planned to be implemented as it should be straightforward. However, we do not have it scheduled it.

**Comment by zhucaoxiang** [comment]
@spollok Great, thank you!

**Comment by spollok** [comment]
@zhucaoxiang I have started documenting on how to read in a customized M-H-curve: https://github.com/cmt-dtu-energy/MagTense/tree/master/python#read-in-cutomized-m-h-curve
Please let me know if something remains unclear.

**Comment by zhucaoxiang** [comment]
@spollok Thanks for the documentation. I was wondering if I can simulate the nonlinear permeability of neodymium magnets using `magnet_type=2` but reading an actual `M-H` curve from neodymium magnets.

**Comment by spollok** [comment]
@zhucaoxiang Unfortunately, this is currently not possible. The direction of the magnetization of `magnet_type=2` will iteratively align with the H-field produced in its center point by all the magnets present in the simulation. Hence, one will loose the magnetic anisotropy of the hard magnet. But that could be a further feature to be implemented soon.
