### ISSUE TITLE
Python package distribution tools

### ISSUE THREAD

**Issue by zhucaoxiang** [cmt-dtu-energy/MagTense#19]
Hi, thanks for helping me get started with using the code #18 .

I think the documentation in the python folder should be updated. For example, I didn't find `../venv/bin/activate` as instructed in https://github.com/cmt-dtu-energy/MagTense/tree/master/python/lib_mag.

I managed to figure out how to install it. I am a fan of installing python packages such that I don't have to modify my PYTHONPATH manually. I made some modifications to the sources, so it can be directly installed using `pip` or `python setup.py install`. I am wondering if you like to update it. If so, I can create a pull request. By doing so, this code can also be distributed via PyPi.
![image](https://user-images.githubusercontent.com/26240833/141821131-0d4e99e6-8925-4731-85ea-1fa40e07268a.png)

**Comment by spollok** [comment]
@zhucaoxiang Thank you very much for your comment. Yes, the documentation was a bit outdated in that folder. We have streamlined it now and moved it to the top python folder: [https://github.com/cmt-dtu-energy/MagTense/tree/master/python](https://github.com/cmt-dtu-energy/MagTense/tree/master/python).

The second point is also a very good idea. You are very welcome to create a pull request. We will then update the documentation once again on how to run MagTense with the Python package distributed via PyPi.

**Comment by zhucaoxiang** [comment]
merged in #20
