### ISSUE TITLE
Tetrahedrons not supported in micromagnetism part

### ISSUE THREAD

**Issue by rasmusbj** [cmt-dtu-energy/MagTense#7]
At present tetrahedrons tiles are not supported in the micromagnetism part.

**Comment by kasparn** [comment]
Yes, that is a tricky one. I don't think we can fix this before we have a robust differential operator that works on a mesh of tetrahedra?

**Comment by rasmusbj** [comment]
No, that is a prerequisite, you are completely right :)

**Comment by rasmusbj** [comment]
Already described in another issue
